#test
test: test

#properties
spring:
  profiles:
    #active: @spring.profile.active@
    active: dev
mybatis:
#  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mappers/*Mapper.xml
  type-aliases-package: com.wormchaos.entity
  configuration:
    map-underscore-to-camel-case: true
